name: Bug report
description: Report an issue with extension behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: Describe the bug and how to reproduce it
      placeholder: e.g. Clicking "Save" crashes if OpenSearch URL is blank
    validations:
      required: true
  - type: input
    id: burp-version
    attributes:
      label: Burp Suite version
      placeholder: e.g. 2025.6.1
  - type: input
    id: java-version
    attributes:
      label: Java version
      placeholder: e.g. OpenJDK 21
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      placeholder: Paste error messages here if available
