name: Feature request
description: Suggest an idea or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What do you want to see?
      description: Clearly describe the feature or improvement
      placeholder: e.g. Add support for exporting extension config to disk
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Why is this useful?
      description: What problem does this solve or improve?
